echo "";
echo "Kalkulator RPN";
echo "Operacje wykonywane tak samo jak w kalkulatorze Unixowym 'dc' (odwrotnosc w stosunku do dzielenia i odejmowania).";
echo "";
echo "Opcje: ";
echo "+ ... dodawanie";
echo "- ... odejmowanie";
echo "x ... mnozenie";
echo "/ ... dzielenie calkowitoliczbowe";
echo "";
echo "P ... usuniecie szczytu stosu";
echo "c ... usuniecie calego stosu";
echo "r ... zamaina dwoch ostatio wprowadzonych danych";
echo "d ... duplikowanie dwoch ostatnio wprowadzonych danych";
echo "p ... wypisanie szczytu stosu";
echo "f ... wypisanie calego stosu";
echo "q ... zakonczenie dzialania";
echo "";
echo "UWAGA!";
echo "Gdy wprowadzisz bledna opcje, np: 'y' to zostanie ona zamieniona na liczbe '0' i dodana jako element do stosu.";
echo "Program nie dziala dla liczb ujemnych (fragment programu napisany na konsultacjach wykluczal opcje odejmowania).";
echo "";
echo "AUTOMATYCZNE TESTY";
echo "Testy przygotowane przeze mnie znajduja sie w skryptach testn.sh, gdzie litera 'n' to numer testu ze sprawozdania.";
echo "Przyklad wywolania testu: /bin/bash test1.sh";
echo "";
echo "Opcja uruchamiania programu z argumentami zostala dodana tylko ze wzgledu na testy.";
echo "Z tego wzgledu obsluguje ona tylko liczby jednocyfrowe.";
echo "Program mozna uruchomic z argumentami wejsciowymi lub bez nich, bez roznicy w dzialaniu.";
echo "";
echo "";
echo "";
echo "";